package librarian

// Dictionary is a map of cyrillic characters to latin characters
var Dictionary = map[string]string{
	"а": "a",
	"б": "b",
	"в": "v",
	"г": "g",
	"д": "d",
	"е": "e",
	"ё": "yo",
	"ж": "zh",
	"з": "z",
	"и": "i",
	"й": "j",
	"к": "k",
	"л": "l",
	"м": "m",
	"н": "n",
	"о": "o",
	"п": "p",
	"р": "r",
	"с": "s",
	"т": "t",
	"у": "u",
	"ф": "f",
	"х": "kh",
	"ц": "ts",
	"ч": "ch",
	"ш": "sh",
	"щ": "shch",
	"ъ": "''",
	"ы": "y",
	"ь": "'",
	"э": "e",
	"ю": "yu",
	"я": "ya",
}

// Associations is a map of latin characters to their associations
var Associations = map[string][]string{
	"a": {"a", "A", "@"},
	"b": {"b", "B", "6"},
	"c": {"c", "C", "("},
	"d": {"d", "D", "|)"},
	"e": {"e", "E", "3", "#", "["},
	"f": {"f", "F", "#"},
	"g": {"g", "G", "9"},
	"h": {"h", "H", "(-)", ")-("},
	"i": {"i", "I", "1", "!"},
	"j": {"j", "J", "1", "]"},
	"k": {"k", "K", "|<"},
	"l": {"l", "L", "1"},
	"m": {"m", "M"},
	"n": {"n", "N"},
	"o": {"o", "O", "0", "()"},
	"p": {"p", "P"},
	"q": {"q", "Q"},
	"r": {"r", "R"},
	"s": {"s", "S"},
	"t": {"t", "T", "+"},
	"u": {"u", "U"},
	"v": {"v", "V", "^"},
	"w": {"w", "W"},
	"x": {"x", "X", "}{", "]["},
	"y": {"y", "Y", "ij"},
	"z": {"z", "Z"},
}
